### PR TITLE
Fixed issue with wx library calls

### PR DESCRIPTION
**Pull request by jhoward321**
some of the calls are in the .adv namespace

### CODE REVIEW

**Comment by devan0** [comment]
Thanks for this, I hadn't updated my wxPython yet.  Have you sent a pull request to seanbuscay?

**Comment by jhoward321** [comment]
I have not. He didn't leave a requirements.txt so I wasn't sure what library versions were needed for that code. Your updated code was much easier to get running. There's another bug with right clicking and closing threads that I was going to fix when I get the time.

**Comment by devan0** [comment]
Yeah I fixed a few bugs, but I'm still seeing the sum of active_time less than how long I think I should have been active. I think there's still a bug in the idle detection code that I want to fix when I get time

**Comment by jhoward321** [comment]
If you'd like to work on it together, let me know. I'm interested in getting this code fully working and updated for both Windows and Linux. I haven't had time to really dig into this code yet but I'll keep the idle detection bug in mind. Going off the readme it looks like the original plan was to support all 3 platforms but this will require some restructuring if we want that to happen.

**Pull request merged**
